### ISSUE TITLE
Always override?

### ISSUE THREAD

**Issue by aubertc** [popbr/abstract_doi_finder#18]
As of now we always override the content of the cells under "doi" & "abstract". Whether this is the right choice is up to debate, but if we maintain this posture, **we need to document it**, so that users won't lose their data.

**Comment by aubertc** [comment]
The comment above is wrong: we actually _never override_?

[test_input.xlsx](https://github.com/popbr/abstract_doi_finder/files/14842890/test_input.xlsx)

**Comment by KingAdam2004** [comment]
I still need to work on this issue, as we still override the data (whether the user provided any or the cell was blank). I have an idea that will keep track of which cells need to be overwritten/populated while keeping any original data that the user may not have wanted to be replaced.

**Comment by KingAdam2004** [comment]
I made some changes with this commit: https://github.com/popbr/abstract_doi_finder/commit/8b03b119c6cefa534dcbf8c1ddd4f3c20258f27d

I am struggling to understand why it is testing true for certain cases, making the entire statement true. I am considering splitting the tests into different statements completely to narrow down what is causing the issue.

**Comment by KingAdam2004** [comment]
This issue is fixed with https://github.com/popbr/abstract_doi_finder/commit/4a47bf3bf51ad5e75a90ac275720cf3ee7115880 and still needs to be properly documented within the README.md file. The file read in the Read_From_Excel method now reads the outputPath file, as it is a replica of the inputPath, but it has additions that happen during the CreateOutput method. Therefore, this fixes the issue of overriding user data when it has a DOI and abstract both present.

**Comment by aubertc** [comment]
I believe this is tested with https://github.com/popbr/abstract_doi_finder/commit/7dbdbc19bb040e9761ea8fe58e6a7ee725d051f0 and hence we can close this issue.
