### ISSUE TITLE
Improve sheet treatment

### ISSUE THREAD

**Issue by aubertc** [popbr/abstract_doi_finder#9]
We could provide two useful upgrades:

- First, skip a sheet if it does not contain, for instance, a row containing "researcher",
- Second, provide as a command-line argument a range. That range could be, for instance,
     - `*` for "all sheets",
     - `2-4` for "sheets from 2 to 4",
     - `2-*` for "sheets from 2 to the end".

Both options together would also help debugging by easily running the program, say, on the 10th sheet if it is problematic.

**Comment by aubertc** [comment]
A lot of progress has been made on this question, and maybe we can close it. It seems that the sheet numbering starts at 0, which could be documented.

**Comment by aubertc** [comment]
Can you either document this, test it more thoroughly, or close this issue, please, @KingAdam2004 ?

**Comment by KingAdam2004** [comment]
I will need to further test this as I added a feature with this commit: https://github.com/popbr/abstract_doi_finder/commit/a03fea59eca109fd6b12dfb0a1bad94a69146ddc

It should work since it has worked throughout my testing thus far, but now users cannot enter 0. I am going to add in an exception to make sure they do not attempt to enter negative numbers as well.

Once I am finished with my testing, I will close this issue.

**Comment by KingAdam2004** [comment]
I have tested this and added further improvements with this commit (https://github.com/popbr/abstract_doi_finder/commit/9c1ae757cc7449e5045c3cd3d5089bfda107cf63). However, I will ask you to test a bit further to ensure that there are no issues since I did not find one.

**Comment by aubertc** [comment]
I have tested it some and it seems to work perfectly.
